apiVersion: v1
kind: ConfigMap
metadata:
  name: edulms-config
  namespace: edulms
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: edulms
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  JWT_ACCESS_EXPIRY: 15m
  JWT_REFRESH_EXPIRY: 168h
  FRONTEND_URL: http://localhost
  AUTH_SERVICE_URL: http://auth-service:8001
  MONGO_URI: mongodb://mongo:27017/edulms
  MINIO_ENDPOINT: minio:9000
  MINIO_BUCKET: edulms-media
  MINIO_USE_SSL: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: edulms-secrets
  namespace: edulms
type: Opaque
stringData:
  POSTGRES_USER: edulms
  POSTGRES_PASSWORD: edulms_secret
  JWT_SECRET: change-me
  REDIS_PASSWORD: redis_secret