apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx-config
  namespace: edulms
data:
  nginx.conf: |
    worker_processes auto;
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      server {
        listen 80;

        location /api/auth/ {
          proxy_pass http://auth-service:8001/;
        }
        location /api/users/ {
          proxy_pass http://user-service:8002/;
        }
        location /api/courses/ {
          proxy_pass http://course-service:8003/;
        }
        location /api/assessments/ {
          proxy_pass http://assessment-service:8004/;
        }
        location /api/attendance/ {
          proxy_pass http://attendance-service:8005/;
        }
        location /api/notifications/ {
          proxy_pass http://notification-service:8006/;
        }
        location /api/payments/ {
          proxy_pass http://payment-service:8010/;
        }

        location = /health {
          default_type application/json;
          return 200 '{"status":"ok"}';
        }
      }
    }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edulms-ingress
  namespace: edulms
spec:
  ingressClassName: nginx
  rules:
    - host: edulms.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
